version: '3'

services:
  minio:
    # Last version with Apache License Version 2.0
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    ports:
      - "9000:9000"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: P@ssw0rd123
    command: server /data

volumes:
  minio_storage: {}
